apiVersion: v1
kind: Pod
metadata:
  name: squid
  labels:
    name: squid
spec:
  containers:
    - name: squid
      image: motionbank/squid:5.7-2
      ports:
        - containerPort: 3128
          protocol: TCP
      volumeMounts:
        - mountPath: /var/spool/squid
          name: data
  volumes:
    - name: data
      emptyDir: {}
